minimum_pre_commit_version: "3.5.0"

ci:
  autofix_prs: true
  autoupdate_schedule: monthly

repos:
  # General hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: detect-private-key
      - id: name-tests-test
        args: ["--pytest-test-first"]

  # Ruff (format + lint fix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]
        additional_dependencies:
          - types-pytz

  # Spelling (docs, README, comments)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words-list=teh,ba,ot,ECT", "--skip=*.lock,*.svg,images/*,htmlcov/*"]

  # Local hooks (optional)
  - repo: local
    hooks:
      # # Prevent direct commits to main
      # - id: no-commit-to-main
      #   name: no-commit-to-main
      #   entry: bash -c 'branch=$(git rev-parse --abbrev-ref HEAD); test "$branch" != "main"'
      #   language: system
      #   pass_filenames: false
      # Quick tests on pre-push
      - id: pytest-quick
        name: pytest (quick)
        entry: uv run pytest -q -k "not concurrent"
        language: system
        pass_filenames: false
        stages: [pre-push]
