name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Sync dependencies
        run: uv sync --group test --group dev
      - name: Lint
        run: |
          uv run ruff format --check .
          uv run ruff check .
      - name: Tests
        run: uv run pytest -q --maxfail=1 --disable-warnings
      - name: Lint Markdown
        run: uv run rumdl check --disable MD013 --output-format github .
      - name: Test for secrets
        run: uv run pysentry-rs .
